#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then to run this script, type that shell name before the whole
#       command line, like:
#
#           ksh gradle
#
#       Busybox and similar reduced shells will NOT work, because this script
#       requires all of these POSIX shell features:
#         * functions;
#         * expansions «$var», «${var}», «${var:-default}», «${var+SET}»,
#           «${var#prefix}», «${var%suffix}», and «$( cmd )»;
#         * compound commands having a testable exit status, especially «case»;
#         * various built-in commands including «command», «set», and «ulimit».
#
#   Important for patching:
#
#   (2) This script targets any POSIX shell, so it avoids extensions provided
#       by Bash, Ksh, etc; in particular arrays are avoided.
#
#       The "traditional" practice of packing multiple parameters into a
#       space-separated string is a well documented source of bugs and security
#       problems, so this is (mostly) avoided, by progressively accumulating
#       options in "$@", and eventually passing that to Java.
#
#       Where the inherited environment variables (DEFAULT_JVM_OPTS, JAVA_OPTS,
#       and GRADLE_OPTS) rely on word-splitting, this is performed explicitly;
#       see the in-line comments for details.
#
#       There are tweaks for specific operating systems such as AIX, CygWin,
#       Darwin, MinGW, and NonStop.
#
#   (3) This script is generated from the Groovy template
#       https://github.com/gradle/gradle/blob/HEAD/subprojects/plugins/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt
#       within the Gradle project.
#
#       You can find Gradle at https://github.com/gradle/gradle/.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit

APP_NAME="Gradle"
APP_BASE_NAME=${0##*/}

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$( uname )" in                #(
  CYGWIN* )         cygwin=true  ;; #(
  Darwin* )         darwin=true  ;; #(
  MSYS* | MINGW* )  msys=true    ;; #(
  NONSTOP* )        nonstop=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(
      max*)
        MAX_FD=$( ulimit -H -n ) ||
            warn "Could not query maximum file descriptor limit"
    esac
    case $MAX_FD in  #(
      '' | soft) :;; #(
      *)
        ulimit -n "$MAX_FD" ||
            warn "Could not set maximum file descriptor limit to $MAX_FD"
    esac
fi

# Collect all arguments for the java command, stacking in reverse order to eventually pass to java.
# We stack in reverse order because the "exec" java command will use the immediate last token as the
# classpath and the first token as the entry point, and we want to give the classpath first because
# that is the conventional usage.

# The order of the stack is this:
#
# 1. classpath (optional, but this script always includes it)
# 2. DEFAULT_JVM_OPTS
# 3. JAVA_OPTS
# 4. GRADLE_OPTS
# 5. main class (org.gradle.wrapper.GradleWrapperMain, always)
# 6. command line arguments

# The stack before app start is empty.
stack=

# This is a scratch variable that holds the index of the current argument being processed.
index=0

# This function processes an argument and adds it to the stack.
process_arg() {
    # If the argument is a double dash, it ends option processing.
    if [ "$1" = "--" ]; then
        # Mark the end of options.
        in_double_dash=1
        return
    fi

    # If we are currently processing options and the argument looks like an option.
    if [ -z "$in_double_dash" ] && [ "${1#-}" != "$1" ]; then
        case $1 in
            # This argument is an option that expects an argument.
            -D* | -J* | -P* | -D?* | -J?* | -P?*)
                stack="$stack \"$1\""
                ;;
            # This argument is an option that does not expect an argument.
            -D | -J | -P)
                # Not currently implemented, but we consume the next argument.
                ;;
            # This is a standard option that does not expect an argument.
            -*)
                stack="$stack \"$1\""
                ;;
            # Anything else is not an option, so we stop option processing.
            *)
                in_double_dash=1
                # Fallthrough to add the argument as a command line argument.
                process_arg "$1"
                ;;
        esac
    else
        # Add the argument to the command line arguments.
        cmdline_args="$cmdline_args \"$1\""
    fi
}

# In Posix shells, there is no array, so we use the stack.  We process arguments in
# reverse because that's the only way to preserve the order we want.

# First, we process the arguments to the script that may affect the environment variable
# GRADLE_APP_BASE_NAME, and the classpath.  We don't know which arguments are which, so we
# just process them all.

# We need to preserve the arguments that we need to process later.
saved_args=

# Initialize the environment variables we need.
in_double_dash=0
index=0
for arg do
    # If we have already processed all the arguments to this script, we are done.
    if [ $index -ge $# ]; then
        break
    fi
    process_arg "$arg"
    index=$((index + 1))
done

# We now have the stack containing the options and the classpath.  We need to reverse it
# to get the correct order for the final command.
stack_rev=
while [ -n "$stack" ]; do
    # Pop the last element from the stack.
    last="${stack##* }"
    stack="${stack% $last}"
    # Remove the surrounding quotes from the last element.
    last="${last#\"}"
    last="${last%\"}"
    # Add it to the reversed stack.
    stack_rev="\"$last\" $stack_rev"
done
stack="$stack_rev"

# Add the classpath.
stack="\"-Dorg.gradle.appname=$APP_BASE_NAME\" -cp \"$CLASSPATH\" org.gradle.wrapper.GradleWrapperMain $stack"

# Add the default JVM options.
for o in $DEFAULT_JVM_OPTS; do
    stack="$stack \"$o\""
done

# Add the JAVA_OPTS and GRADLE_OPTS environment variables.
for o in $JAVA_OPTS $GRADLE_OPTS; do
    stack="$stack \"$o\""
done

# Add the command line arguments to the stack.
for o in $cmdline_args; do
    stack="$stack \"$o\""
done

# Execute the java command, capturing the output for later.
exec "$JAVACMD" $stack
